 runtime: php55
 api_version: 1


 handlers:

 - url: /test2
   script: www/test2.php

 - url: /registertest
   script: www/registertest.php

 - url: /api/.*
   script: www/api.php

 - url: /assets
   static_dir: www/assets

 - url: /logout
   script: www/logout.php

 - url: /event/create
   script: www/createeventScript.php

 - url: /event/login
   script: www/process_login.php

 - url: /register
   script: www/register.php

 - url: /.*
   script: www/main.php

