 runtime: php55
 api_version: 1


 handlers:


 - url: /test
   static_dir: www/test.php

 - url: /api/.*
   static_dir: www/api.php

 - url: /assets
   static_dir: www/assets

 - url: /login
   script: www/login.php

 - url: /register
   script: www/register.php


 - url: /.*
   script: www/main.php

