 runtime: php55
 api_version: 1


 handlers:

 - url: /test2
   script: www/test2.php

 - url: /registertest
   script: www/registertest.php

 - url: /api/.*
   script: www/api.php

 - url: /assets
   static_dir: www/assets

 - url: /login
   script: www/login.php

 - url: /register
   script: www/register.php

 - url: /.*
   script: www/main.php

