 runtime: php55
 api_version: 1

 handlers:


 - url: /api
   static_dir: www/index.php


 - url: /assets
   static_dir: www2/assets

 - url: /login
   script: www2/login.php

 - url: /register
   script: www2/register.php

 - url: /test
   script: www2/Testdb.php

 - url: /.*
   script: www2/main.php

