 runtime: php55
 api_version: 1


 handlers:

 - url: /test2
   script: www/test2.php

 - url: /upload_handler
   script: www/upload_handler.php

 - url: /register
   script: www/register_script.php

 - url: /api/.*
   script: www/api.php

 - url: /assets
   static_dir: www/assets

 - url: /logout
   script: www/logout.php

 - url: /event/create
   script: www/createeventScript.php

 - url: /login
   script: www/process_login.php

 - url: /register
   script: www/register.php

 - url: /.*
   script: www/main.php

