 runtime: php55
 api_version: 1

 handlers:
 - url: /assets
   static_dir: www/assets

 - url: /login2
   script: www/login.php

 - url: /register
   script: www/register.php

 - url: /.*
   script: www/main.php

